{{- if .Values.admissionController.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "kyverno.admission-controller.name" . }}
  namespace: {{ template "kyverno.namespace" . }}
  labels:
  {{- include "kyverno.admission-controller.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "kyverno.admission-controller.name" . }}
  minReplicas: {{ .Values.admissionController.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.admissionController.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.admissionController.autoscaling.targetCPUUtilizationPercentage }}
    - resource:
        name: cpu
        target:
          averageUtilization: {{ .Values.admissionController.autoscaling.targetCPUUtilizationPercentage }}
          type: Utilization
      type: Resource
    {{- end }}
    {{- if .Values.admissionController.autoscaling.targetMemoryUtilizationPercentage }}
    - resource:
        name: memory
        target:
          averageUtilization: {{ .Values.admissionController.autoscaling.targetMemoryUtilizationPercentage }}
          type: Utilization
      type: Resource
    {{- end }}
  {{- with .Values.admissionController.autoscaling.behavior }}
  behavior:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
