apiVersion: v2
type: application
name: kyverno-policies
version: 2.6.2
appVersion: v1.8.2
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Kubernetes Pod Security Standards implemented as Kyverno policies
keywords:
  - kubernetes
  - nirmata
  - policy agent
  - validating webhook
  - admissions controller
home: https://kyverno.io/policies/
sources:
  - https://github.com/kyverno/policies
maintainers:
  - name: Nirmata
    url: https://kyverno.io/
kubeVersion: ">=1.16.0-0"
annotations:
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  # valid kinds are: added, changed, deprecated, removed, fixed and security
  artifacthub.io/changes: |
    - kind: added
      description: Add possibility to manually set kyvernoVersion and avoid autodetection
    - kind: added
      description: Support for artifacthub.io/changes annotation
    - kind: fixed
      description: Fix Kyverno version check when image tag contains registry port number
    - kind: fixed
      description: Ensure preconditions are present with default values
    - kind: added
      description: Support for failurePolicy setting in kyverno-policies helm chart
    - kind: added
      description: Add possibility to set validationFailureAction by Policy
    - kind: added
      description: Added ability to get additional policies from restricted
    - kind: fixed
      description: Applied fix in preconditions for background mode
    - kind: added
      description: Added case insensitivity guarantees to disallow-capabilities-strict
