apiVersion: v1
type: application
name: kyverno-policies
version: v2.3.0
appVersion: v1.6.0
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Kubernetes Pod Security Standards implemented as Kyverno policies
keywords:
  - kubernetes
  - nirmata
  - policy agent
  - validating webhook
  - admissions controller
home: https://kyverno.io/policies/
sources:
  - https://github.com/kyverno/policies
maintainers:
  - name: Nirmata
    url: https://kyverno.io/
kubeVersion: ">=1.16.0-0"
