apiVersion: v2
type: application
name: kyverno-policies
version: v3.1.1
appVersion: latest
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Kubernetes Pod Security Standards implemented as Kyverno policies
keywords:
  - kubernetes
  - nirmata
  - policy agent
  - validating webhook
  - admissions controller
home: https://kyverno.io/policies/
sources:
  - https://github.com/kyverno/policies
maintainers:
  - name: kyverno-maintainers
    email: cncf-kyverno-maintainers@lists.cncf.io
kubeVersion: ">=1.16.0-0"
annotations:
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"