initContainer:
  extraArgs:
    - --loggingFormat=json

extraArgs:
  - --loggingFormat=json
  - --enablePolicyException

cleanupController:
  rbac:
    clusterRole:
      extraResources:
        - apiGroups:
            - ''
          resources:
            - pods

backgroundController:
  rbac:
    clusterRole:
      extraResources:
        - apiGroups:
            - '*'
          resources:
            - configmaps
            - secrets
            - roles
            - rolebindings
            - limitranges
            - namespaces
            - nodes
            - nodes/status
            - pods

  extraArgs:
    - --enablePolicyException
