initContainer:
  extraArgs:
    - --loggingFormat=json

extraArgs:
  - --loggingFormat=json
  - --enablePolicyException
  - --exceptionNamespace=kyverno

cleanupController:
  rbac:
    clusterRole:
      extraResources:
        - apiGroups:
            - ''
          resources:
            - pods

reportsController:
  extraArgs:
    - --enablePolicyException

backgroundController:
  rbac:
    clusterRole:
      extraResources:
        - apiGroups:
            - '*'
          resources:
            - configmaps
            - secrets
            - roles
            - rolebindings
            - limitranges
            - namespaces
            - nodes
            - nodes/status
            - pods
