apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./clusterroles.yaml
- ./clusterrolebindings.yaml
- ./configmap.yaml
- ./namespace.yaml
- ./service.yaml
- ./serviceaccount.yaml
- ./poddisruptionbudget.yaml