blank_issues_enabled: false
contact_links:
  - name: Kyverno Community Support (#kyverno channel on the Kubernetes Slack) 
    url: https://kubernetes.slack.com/archives/CLGR9BJU9
    about: Please ask and answer any Kyverno usage questions here.
  - name: Kyverno Contributor Discussions
    url: https://github.com/kyverno/kyverno/discussions
    about: Please ask and answer questions Kyverno internals questions here.

