# -- Internal settings used with `helm template` to generate install manifest
# @ignored
templating:
  enabled: false
  debug: false
  version: ~

groups:

  # -- Install CRDs in group `kyverno.io`
  # -- This field can be overwritten by setting crds.labels in the parent chart
  kyverno: true

  # -- Install CRDs in group `wgpolicyk8s.io`
  # -- This field can be overwritten by setting crds.labels in the parent chart
  wgpolicyk8s: true

  # -- Install CRDs in group `reports.kyverno.io`
  # -- This field can be overwritten by setting crds.labels in the parent chart
  reports: true

# -- Additional CRDs annotations
# -- This field can be overwritten by setting crds.annotations in the parent chart
annotations: {}
  # argocd.argoproj.io/sync-options: Replace=true
  # strategy.spinnaker.io/replace: 'true'

# -- Additional CRDs labels
# -- This field can be overwritten by setting crds.labels in the parent chart
customLabels: {}
