{{- $name := "disallow-host-ports" }}
{{- if and (eq (include "kyverno-policies.podSecurityBaseline" (merge (dict "name" $name) .)) "true") (eq (include "kyverno-policies.useValidatingPolicy" .) "true") }}
apiVersion: policies.kyverno.io/v1beta1
kind: ValidatingPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Disallow hostPorts
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    {{- if .Values.podSecuritySeverity }}
    policies.kyverno.io/severity: {{ .Values.podSecuritySeverity }}
    {{- end }}
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: {{ default .Chart.AppVersion (include "kyverno-policies.kyvernoVersion" .) }}
    kyverno.io/kubernetes-version: "{{ default .Chart.KubeVersion .Values.kubeVersionOverride }}"
    policies.kyverno.io/description: >-
      Access to host ports allows potential snooping of network traffic and should not be
      allowed, or at minimum restricted to a known list. This policy ensures the `hostPort`
      field is unset or set to `0`.
    {{- include "kyverno-policies.customAnnotations" . | nindent 4 }}
  labels: {{ include "kyverno-policies.labels" . | nindent 4 }}
spec:
  failurePolicy: {{ .Values.failurePolicy }}
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: [v1]
      operations: [CREATE, UPDATE]
      resources: [pods]
  validations:
    - expression: >-
        (!has(object.spec.containers) || object.spec.containers.all(c, 
          !has(c.ports) || c.ports.all(p, !has(p.hostPort) || p.hostPort == 0))) &&
        (!has(object.spec.initContainers) || object.spec.initContainers.all(c, 
          !has(c.ports) || c.ports.all(p, !has(p.hostPort) || p.hostPort == 0))) &&
        (!has(object.spec.ephemeralContainers) || object.spec.ephemeralContainers.all(c, 
          !has(c.ports) || c.ports.all(p, !has(p.hostPort) || p.hostPort == 0)))
      message: >-
        Use of host ports is disallowed. The fields spec.containers[*].ports[*].hostPort
        , spec.initContainers[*].ports[*].hostPort, and spec.ephemeralContainers[*].ports[*].hostPort
        must either be unset or set to `0`.
  {{- $actions := include "kyverno-policies.policyValidationActions" (dict "name" $name "values" .Values) }}
  validationActions: {{ $actions | nindent 4 }}
{{- end }}

