{{- $name := "disallow-proc-mount" }}
{{- if and (eq (include "kyverno-policies.podSecurityBaseline" (merge (dict "name" $name) .)) "true") (eq (include "kyverno-policies.useValidatingPolicy" .) "true") }}
apiVersion: policies.kyverno.io/v1beta1
kind: ValidatingPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Disallow /proc Mount Type
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    {{- if .Values.podSecuritySeverity }}
    policies.kyverno.io/severity: {{ .Values.podSecuritySeverity }}
    {{- end }}
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: {{ default .Chart.AppVersion (include "kyverno-policies.kyvernoVersion" .) }}
    kyverno.io/kubernetes-version: "{{ default .Chart.KubeVersion .Values.kubeVersionOverride }}"
    policies.kyverno.io/description: >-
      The default /proc masks are set up to reduce attack surface and should be required.
      This policy ensures the `procMount` field is unset or set to `Default`.
    {{- include "kyverno-policies.customAnnotations" . | nindent 4 }}
  labels: {{ include "kyverno-policies.labels" . | nindent 4 }}
spec:
  failurePolicy: {{ .Values.failurePolicy }}
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: [v1]
      operations: [CREATE, UPDATE]
      resources: [pods]
  validations:
    - expression: >-
        (!has(object.spec.containers) || object.spec.containers.all(c, 
          !has(c.securityContext) || 
          !has(c.securityContext.procMount) || 
          c.securityContext.procMount == 'Default')) &&
        (!has(object.spec.initContainers) || object.spec.initContainers.all(c, 
          !has(c.securityContext) || 
          !has(c.securityContext.procMount) || 
          c.securityContext.procMount == 'Default')) &&
        (!has(object.spec.ephemeralContainers) || object.spec.ephemeralContainers.all(c, 
          !has(c.securityContext) || 
          !has(c.securityContext.procMount) || 
          c.securityContext.procMount == 'Default'))
      message: >-
        The default /proc masks are set up to reduce attack surface. The fields
        spec.containers[*].securityContext.procMount,
        spec.initContainers[*].securityContext.procMount, and
        spec.ephemeralContainers[*].securityContext.procMount must be unset or set to `Default`.
  {{- $actions := include "kyverno-policies.policyValidationActions" (dict "name" $name "values" .Values) }}
  validationActions: {{ $actions | nindent 4 }}
{{- end }}

