apiVersion: v1
data:
  resourceFilters: >
    [Event,*,*]
    [*,kube-system,*]
    [*,kube-public,*]
    [*,kube-node-lease,*]
    [*,kyverno,*]
    [Node,*,*]
    [APIService,*,*]
    [TokenReview,*,*]
    [SubjectAccessReview,*,*]
    [SelfSubjectAccessReview,*,*]
    [*,kyverno,kyverno*]
    [Binding,*,*]
    [ReplicaSet,*,*]
    [AdmissionReport,*,*]
    [ClusterAdmissionReport,*,*]
    [BackgroundScanReport,*,*]
    [ClusterBackgroundScanReport,*,*]
    [PolicyReport,*,*]
    [ClusterPolicyReport,*,*]
  webhooks: '[{"namespaceSelector": {"matchExpressions": [{"key":"kubernetes.io/metadata.name","operator":"NotIn","values":["kyverno"]}]}}]'
  excludeGroupRole: 'system:serviceaccounts:kube-system,system:nodes,system:kube-scheduler'
  generateSuccessEvents: 'false'
kind: ConfigMap
metadata:
  labels:
    app: kyverno
  name: kyverno
