---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kyverno:leaderelection
  labels:
    app: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyverno:leaderelection
subjects:
- kind: ServiceAccount
  name: kyverno-service-account
# ---
# # Additional permission is required to enable DryRun.
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: manifest-verify-dry-run
#   namespace: kyverno
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: manifest-verify-dry-run
# subjects:
# - kind: ServiceAccount
#   name: kyverno-service-account
#   namespace: kyverno