policies:
  - name: limit-configmap-for-sa
    resources:
      - name: any-configmap-name-good
        values:
          request.operation: UPDATE
      - name: any-configmap-name-bad
        values:
          request.operation: UPDATE

namespaceSelector:
  - name: test1
    labels:
      foo.com/managed-state: managed
