apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../bundle/

transformers:
- labels.yaml

images:
- name: ghcr.io/kyverno/kyverno
  newTag: v1.6.2
- name: ghcr.io/kyverno/kyvernopre
  newTag: v1.6.2
