{{- if .Values.cleanupJobs.clusterAdmissionReports.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "kyverno.name" . }}-cleanup-cluster-admission-reports
  namespace: {{ template "kyverno.namespace" . }}
  labels:
    {{- include "kyverno.cleanup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cleanupJobs.clusterAdmissionReports.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.cleanupJobs.clusterAdmissionReports.history.success }}
  failedJobsHistoryLimit: {{ .Values.cleanupJobs.clusterAdmissionReports.history.failure }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.cleanupJobs.clusterAdmissionReports.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cleanupJobs.clusterAdmissionReports.podLabels }}
          labels:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ template "kyverno.name" . }}-cleanup-jobs
          {{- with .Values.cleanupJobs.clusterAdmissionReports.podSecurityContext }}
          securityContext:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          containers:
          - name: cleanup
            image: {{ (include "kyverno.image" (dict "globalRegistry" ((.Values.global).image).registry "image" .Values.cleanupJobs.clusterAdmissionReports.image)) | quote }}
            imagePullPolicy: {{ .Values.cleanupJobs.clusterAdmissionReports.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - |
              COUNT=$(kubectl get clusteradmissionreports.kyverno.io -A | wc -l)
              if [ "$COUNT" -gt {{ .Values.cleanupJobs.clusterAdmissionReports.threshold }} ]; then
                echo "too many reports found ($COUNT), cleaning up..."
                kubectl delete clusteradmissionreports.kyverno.io -A -l='!audit.kyverno.io/report.aggregate'
              else
                echo "($COUNT) reports found, no clean up needed"
              fi
            {{- with .Values.cleanupJobs.clusterAdmissionReports.securityContext }}
            securityContext:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.cleanupJobs.clusterAdmissionReports.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- with .Values.cleanupJobs.clusterAdmissionReports.imagePullSecrets }}
          imagePullSecrets:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          {{- with .Values.cleanupJobs.clusterAdmissionReports.tolerations }}
          tolerations:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.cleanupJobs.clusterAdmissionReports.nodeSelector }}
          nodeSelector:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- if or .Values.cleanupJobs.clusterAdmissionReports.podAntiAffinity .Values.cleanupJobs.clusterAdmissionReports.podAffinity .Values.cleanupJobs.clusterAdmissionReports.nodeAffinity }}
          affinity:
            {{- with .Values.cleanupJobs.clusterAdmissionReports.podAntiAffinity }}
            podAntiAffinity:
              {{- tpl (toYaml .) $ | nindent 14 }}
            {{- end }}
            {{- with .Values.cleanupJobs.clusterAdmissionReports.podAffinity }}
            podAffinity:
              {{- tpl (toYaml .) $ | nindent 14 }}
            {{- end }}
            {{- with .Values.cleanupJobs.clusterAdmissionReports.nodeAffinity }}
            nodeAffinity:
              {{- tpl (toYaml .) $ | nindent 14 }}
            {{- end }}
          {{- end }}
{{- end -}}
