{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kyverno.config.configMapName" . }}
  namespace: {{ template "kyverno.namespace" . }}
  labels:
    {{- include "kyverno.config.labels" . | nindent 4 }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  enableDefaultRegistryMutation: {{ .Values.config.enableDefaultRegistryMutation | quote }}
  {{- with .Values.config.defaultRegistry }}
  defaultRegistry: {{ . | quote }}
  {{- end }}
  generateSuccessEvents: {{ .Values.config.generateSuccessEvents | quote }}
  {{- with .Values.config.excludeGroupRole }}
  excludeGroupRole: {{ join "," . | quote }}
  {{- end -}}
  {{- $username := (printf "system:serviceaccount:%s:%s" (include "kyverno.namespace" .) (include "kyverno.background-controller.serviceAccountName" .)) }}
  {{- if .Values.config.excludeUsername }}
  {{- $username = prepend .Values.config.excludeUsername $username}}
  excludeUsername: {{ join "," $username | quote }}
  {{- else }}
  excludeUsername: {{ $username }}
  {{- end -}}  
  {{- if .Values.config.resourceFilters }}
  resourceFilters: {{ include "kyverno.config.resourceFilters" . | quote }}
  {{- end -}}
  {{- if and .Values.config.webhooks .Values.excludeKyvernoNamespace }}
  webhooks: {{ include "kyverno.config.webhooks" . | quote }}
  {{- else if .Values.config.webhooks }}
  webhooks: {{ .Values.config.webhooks | toJson | quote }}
  {{- else if .Values.excludeKyvernoNamespace }}
  webhooks: '[{"namespaceSelector": {"matchExpressions": [{"key":"kubernetes.io/metadata.name","operator":"NotIn","values":["{{ include "kyverno.namespace" . }}"]}]}}]'
  {{- end -}}
{{- end -}}
