name: cli

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'
      - 'release*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cli-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Setup build env
        uses: ./.github/actions/setup-build-env
        with:
          build-cache-key: cli-test
      - name: Setup TEST_GIT_BRANCH
        run: |
          if [[ ${{ github.event_name }} == "push" ]]
          then
            export TEST_GIT_BRANCH=${GITHUB_REF##*/}
          elif [[ ${{ github.event_name }} == "pull_request" ]]
          then
            export TEST_GIT_BRANCH=${{ github.event.pull_request.base.ref }}
          fi
      - name: Test CLI
        run: |
          VERSION=${{ github.ref_name }} make test-cli
      - name: Test CLI (failures)
        run: |
          CLI_PATH=$PWD/cmd/cli/kubectl-kyverno/kubectl-kyverno
          $CLI_PATH test ./test/cli/test-fail/missing-policy && exit 1 || exit 0
          $CLI_PATH test ./test/cli/test-fail/missing-rule && exit 1 || exit 0
          $CLI_PATH test ./test/cli/test-fail/missing-resource && exit 1 || exit 0
