name: e2e-autogen-internals
on:
  push:
    branches:
      - 'main'
      - 'release*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.github/config.yml'
  pull_request:
    branches:
      - 'main'
      - 'release*'
    paths-ignore:
      - 'README.md'
      - '.github/config.yml'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-test:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.22.13, v1.23.10, v1.24.4, v1.25.0]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go 
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.4.0
        with:
          go-version: ~1.18.6

      - name: Set up Helm
        uses: azure/setup-helm@f382f75448129b3be48f8121b9857be18d815a82 # v3.4
        with:
          version: v3.5.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@afea100a513515fbd68b0e72a7bb0ae34cb62aec # v2.3.1

      - name: Cache Go modules
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # pin@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Create dev images, kind cluster and setup kustomize
        run: |
          export KIND_IMAGE=kindest/node:${{ matrix.k8s-version }}
          make create-e2e-infrastructure

      - name: e2e testing
        run: |
          echo ">>> Install Kyverno"
          cat ${GITHUB_WORKSPACE}/config/install.yaml | \
          sed -e 's/imagePullPolicy:.*$/imagePullPolicy: IfNotPresent/g' | \
          kubectl create -f -
          kubectl apply -f ${GITHUB_WORKSPACE}/config/github/rbac.yaml
          chmod a+x ${GITHUB_WORKSPACE}/scripts/verify-deployment.sh
          sleep 50
          echo ">>> Check kyverno"
          kubectl get pods -n kyverno
          ${GITHUB_WORKSPACE}/scripts/verify-deployment.sh -n kyverno  kyverno
          sleep 20
          echo ">>> Expose the Kyverno's service's metric server to the host"
          kubectl port-forward svc/kyverno-svc-metrics -n kyverno 8000:8000 &
          echo ">>> Run Kyverno e2e test"
          make test-e2e
          kubectl delete -f ${GITHUB_WORKSPACE}/config/install.yaml

      - name: Debug failure
        if: failure()
        run: |
          kubectl get mutatingwebhookconfigurations,validatingwebhookconfigurations
          kubectl -n kyverno get pod
          kubectl -n kyverno describe pod | grep -i events -A10
          kubectl -n kyverno logs deploy/kyverno --all-containers -p || true
          kubectl -n kyverno logs deploy/kyverno --all-containers
          kubectl -n kyverno logs deploy/kyverno-cleanup-controller --all-containers -p || true
          kubectl -n kyverno logs deploy/kyverno-cleanup-controller --all-containers
