name: helm-test

on:
  pull_request:
    branches:
      - main
      - release*
    paths:
      - charts/**
      - .github/workflows/helm-test.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  helm-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup build env
        uses: ./.github/actions/setup-build-env
      - name: Setup python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@afea100a513515fbd68b0e72a7bb0ae34cb62aec # v2.3.1
      - name: Run chart-testing (lint)
        run: |
          if [[ $(ct list-changed --target-branch=main) ]];
          then
            ct lint --target-branch=main --check-version-increment=false
          fi
      - name: Setup test env
        uses: ./.github/actions/setup-test-env
        with:
          build-cache-key: helm-tests
      - name: Helm test
        run: make helm-test
      - name: Debug failure
        if: failure()
        uses: ./.github/actions/kyverno-logs
