# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Retry workflow

permissions: {}

on:
  workflow_run:
    workflows:
      - Build devcontainer
      - Conformance tests
    types: 
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rerun:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt < 3 }}
    steps:
      - name: Rerun ${{ github.event.workflow_run.id }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run watch ${{ github.event.workflow_run.id }}
          gh run rerun ${{ github.event.workflow_run.id }} --failed
