# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Verify codegen

permissions: {}

on:
  pull_request:
    branches:
    - main
    - release-*
    paths:
    - 'api/**'
    - 'charts/**'
    - 'cmd/cli/kubectl-kyverno/apis/**'
    - 'hack/**'
    - 'scripts/boilerplate.go.txt'
    - 'docs/user/template/**'
    - 'docs/user/config*.yaml'
    - 'docs/user/config.json'
    - 'Makefile'
    - 'go.mod'
    - 'go.sum'
    - '.github/workflows/verify-codegen.yaml'
    - '.github/actions/setup-build-env/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-codegen-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: go.mod
        cache-dependency-path: "**/*.sum"
    - name: Cache tools
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: .tools
        key: tools-${{ runner.os }}-${{ hashFiles('Makefile') }}
        restore-keys: |
          tools-${{ runner.os }}-
    - name: Generate code
      run:  |
        set -e
        make codegen-all-code
    - name: Verify codegen is up to date
      run:  |
        set -e
        make verify-codegen

  verify-codegen-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: go.mod
        cache-dependency-path: "**/*.sum"
    - name: Cache tools
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: .tools
        key: tools-${{ runner.os }}-${{ hashFiles('Makefile') }}
        restore-keys: |
          tools-${{ runner.os }}-
    - name: Generate api docs
      run:  |
        set -e
        make codegen-all-docs
    - name: Verify codegen is up to date
      run:  |
        set -e
        make verify-codegen

  verify-codegen-success:
    name: verify-codegen
    needs:
      - verify-codegen-code
      - verify-codegen-docs
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - run: ${{ true }}

  verify-codegen-failure:
    name: verify-codegen
    needs:
      - verify-codegen-code
      - verify-codegen-docs
    runs-on: ubuntu-latest
    if: ${{ failure() || cancelled() }}
    steps:
      - run: ${{ false }}
